version: '3.3'

volumes:
  pg_data:
  static_backend:
  static_frontend:
  media_backend:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  frontend:
    image: agas0077/foodgram-frontend:latest
    volumes:
      - static_frontend:/app/result_build/


  backend:
    image: agas0077/foodgram-backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_backend:/app/static/
      - media_backend:/app/backend_media
    command: >
      bash -c "python manage.py migrate 
      && python manage.py collectstatic --no-input
      && python manage.py load_ingredients
      && python manage.py load_tags
      && gunicorn --bind 0.0.0.0:8001 backend.wsgi"
  
  nginx:
    depends_on:
        - backend
        - frontend
    image: agas0077/foodgram-gateway:latest
    ports:
      - "8000:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/build:/usr/share/nginx/html/
      # - ./docs/:/usr/share/nginx/html/api/docs/ 
      - static_backend:/static_backend
      - static_frontend:/static_frontend
      - media_backend:/media_backend