GET http://localhost:8000/api/recipes/
?tags=Black
&tags=Black
Authorization: Token 2d3f9bd105f540e6d134c0d400cc4ddf4db79cd0

###
POST http://localhost:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "a@aa.aa",
    "password": "a"
}

###
GET http://localhost:8000/api/ingredients/
Authorization: Token 2d3f9bd105f540e6d134c0d400cc4ddf4db79cd0

###
POST http://localhost:8000/api/recipes/57/shopping_cart/
Authorization: Token 2d3f9bd105f540e6d134c0d400cc4ddf4db79cd0

###
DELETE http://localhost:8000/api/recipes/1/shopping_cart/
Authorization: Token 2d3f9bd105f540e6d134c0d400cc4ddf4db79cd0


###
GET http://localhost:8000/api/recipey/download_shopping_cart/
Authorization: Token 2d3f9bd105f540e6d134c0d400cc4ddf4db79cd0

