
PATCH http://localhost:8000/api/recipes/73/
Content-Type: application/json
Authorization: Token 2d3f9bd105f540e6d134c0d400cc4ddf4db79cd0

{
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}
###
GET  http://localhost:8000/api/recipes/
Authorization: Token 2d3f9bd105f540e6d134c0d400cc4ddf4db79cd0


###

POST http://localhost:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "a@aa.aa",
    "password": "a"
}