# Generated by Django 4.2.2 on 2023-07-14 18:10

# Third Party Library
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingredientlist", "0003_userrecipeingredient_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_ingredient_ingredient",
                to="ingredientlist.ingredient",
                verbose_name="recipe_ingredient_ingredient",
            ),
            preserve_default=False,
        ),
    ]
