# Generated by Django 4.2.2 on 2023-07-17 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_remove_recipe_ingredients"),
        ("ingredientlist", "0007_recipeingredient_delete_userrecipeingredient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeIngredient",
            new_name="IngredientRecipe",
        ),
    ]
