# Generated by Django 4.2.2 on 2023-07-18 18:56

# Third Party Library
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0014_remove_recipe_shopping_cart_recipe_in_shopping_cart_and_more",
        ),
        ("ingredientlist", "0008_rename_recipeingredient_ingredientrecipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(max_length=50, verbose_name="Единица измерения"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название ингредиента"),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Объем/количество",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_ingredient_ingredient",
                to="ingredientlist.ingredient",
                verbose_name="Название ингредиента",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_ingredient_recipe",
                to="recipes.recipe",
                verbose_name="Название рецепта",
            ),
        ),
    ]
