# Generated by Django 4.2.2 on 2023-07-23 22:29

# Third Party Library
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0014_remove_recipe_shopping_cart_recipe_in_shopping_cart_and_more",
        ),
        ("ingredientlist", "0009_alter_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredient_recipe",
                to="recipes.recipe",
                verbose_name="Название рецепта",
            ),
        ),
    ]
