# Generated by Django 4.2.2 on 2023-07-07 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[A-Z0-9]+$", "Check you HEX code"
                    )
                ],
                verbose_name="Tag color",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[-a-zA-Z0-9_]+$",
                        "Your slug must contain only letters, digits or _ and -",
                    )
                ],
                verbose_name="Tag slug",
            ),
        ),
    ]
