# Generated by Django 4.2.2 on 2023-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_remove_recipe_user_likes_favorite"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"),
                name="unique_favorite",
                violation_error_message="Нельзя дважды добавить в избранное!",
            ),
        ),
    ]
