# Generated by Django 4.2.2 on 2023-07-07 13:58

# Third Party Library
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_recipe_tags_recipetag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipetag",
            old_name="Recipe",
            new_name="recipe",
        ),
    ]
