# Generated by Django 4.2.2 on 2023-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_rename_recipe_recipetag_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipetag",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="tag",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(related_name="recipe_list", to="recipes.tag"),
        ),
    ]
