# Generated by Django 4.2.2 on 2023-07-10 20:39

# Third Party Library
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0005_remove_recipetag_recipe_remove_recipetag_tag_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeTag",
        ),
        migrations.AddField(
            model_name="recipe",
            name="user_likes",
            field=models.ManyToManyField(
                related_name="recipe_like_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Like",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipe_list", to="recipes.tag", verbose_name="Tag"
            ),
        ),
    ]
