# Generated by Django 4.2.2 on 2023-07-11 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_delete_recipetag_recipe_user_likes_alter_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="publishing_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 7, 11, 20, 41, 26, 72890),
                verbose_name="publishing date",
            ),
            preserve_default=False,
        ),
    ]
