# Generated by Django 4.2.2 on 2023-07-11 23:14

# Third Party Library
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0007_recipe_publishing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="publishing_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="publishing_date"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipe_list",
                to="recipes.tag",
                verbose_name="Tag",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="user_likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipe_like_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Like",
            ),
        ),
    ]
