# Generated by Django 4.2.2 on 2023-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredientlist", "0001_initial"),
        ("recipes", "0010_recipe_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                to="ingredientlist.ingredient",
                verbose_name="ingredient list",
            ),
        ),
    ]
