# Generated by Django 4.2.2 on 2023-07-14 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0011_remove_recipe_ingredients_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="shopping_cart",
            field=models.ManyToManyField(
                blank=True,
                related_name="shopping_cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="shopping_cart",
            ),
        ),
    ]
