# Generated by Django 4.2.2 on 2023-07-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubscriberSubscribee",
            new_name="Subscription",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "subscribee"), name="unique_subscription"
            ),
        ),
    ]
