# Generated by Django 4.2.2 on 2023-07-05 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email_subscribersubscribee"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscribersubscribee",
            unique_together={("subscriber", "subscribee")},
        ),
    ]
