# Generated by Django 4.2.2 on 2023-07-18 18:56

# Third Party Library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_subscribersubscribee_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribersubscribee",
            name="subscribee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscribee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="На кого подписывается",
            ),
        ),
        migrations.AlterField(
            model_name="subscribersubscribee",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто подписывается",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Адрес электронной почты"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
    ]
